awards/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls')),
    path('users/', include('posts.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path('profile/<username>/', profile, name='profile'),
    path('edit-profile/', edit_profile, name='edit_profile'),
    path('api/v1/profiles/', profileList, name='profiles'),
]

posts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from.models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email")

class LoginForm(forms.Form):
    email = forms.CharField()
    password = forms.CharField()




class EditProfileForm(forms.Form):
    username = forms.CharField()
    bio = forms.CharField(widget=forms.Textarea())
    image = forms.FileField(required=False)

    def __init__(self, original_username, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.original_username = original_username

    def clean_username(self):
        """
        This function throws an exception if the username has already been 
        taken by another user
        """

        username = self.cleaned_data['username']
        if username != self.original_username:
            if User.objects.filter(username=username).exists():
                raise forms.ValidationError(
                    'A user with that username already exists.')
        return username

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>
        {% block title %} {% endblock %}
    </title>
  </head>
  <body>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" style="margin-top: 5rem;">
      {{message}}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/details.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Awards</title>

    <!-- css mdb -->

    <!-- Font Awesome -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
    />
    <!-- MDB -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.1.0/mdb.min.css"
      rel="stylesheet"
    />

    <!-- custom css -->

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

  </head>
  <body>

   
    <!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <!-- Container wrapper -->
    <div class="container-fluid">
      <!-- Toggle button -->
      <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars"></i>
      </button>
  
      <!-- Collapsible wrapper -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Navbar brand -->
        <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'home' %}">
        <h5>Awwards</h5>
        </a>
        <!-- Left links -->
        <!-- <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="#">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Team</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Projects</a>
          </li>
        </ul> -->
        <!-- Left links -->
      </div>

      <form class="d-flex input-group w-auto">
        <input
          type="search"
          class="form-control rounded"
          placeholder="Search"
          aria-label="Search"
          aria-describedby="search-addon"
        />
        <span class="input-group-text border-0" id="search-addon">
          <i class="fas fa-search"></i>
        </span>
      </form>
      <!-- Collapsible wrapper -->
  
      <!-- Right elements -->
      <div class="d-flex align-items-center">
        {% if request.user.is_authenticated %}
        <a class="text-reset me-3" href="#">
          <a href="{% url 'postproject' %}" class="btn btn-dark" href="#">SUBMIT YOUR SITE !</a>
          <a href="{% url 'profile' request.user.username %}"
          class="nav-item nav-link {% if request.user.username in request.path %}active{% endif %}">
          Profile page
       </a>
         </a>
         {% else %}
         <a class="text-reset me-3" href="#">
          <a href="{% url 'signup' %}" class="nav-item nav-link">Register</a>
          <a href="{% url 'login' %}" class="nav-item nav-link">login</a>
          </a>
         {% endif %}
       
  
       
      </div>
      <!-- Right elements -->
    </div>
    <!-- Container wrapper -->
  </nav>
  <!-- Navbar -->

  <!-- hero -->

<div class="main">
    <div class="container">

        <p class="text-white">Site of the Day 12th June 2022</p>
        <div class="row mt-4">
            <div class="col-md-3"></div>
            <div class="col-md-6">
    
                <h1 class="mt-4 text-center">Marble</h1>
    
                <p class="mt-2 text-center">By {{project.user.username}}</p>
    
                <div class="row text-center">
    
                    <div class="rating">9</div>

                    <div class="rating">5</div>
                    
                    <div class="rating">2</div>
    
            
                </div>
    
    
            </div>
            <div class="col-md-3"></div>
        </div>

        <button class="btn btn-info mt-4">visit site</button>
        <button class="btn btn-outline-white mt-4">Collect</button>
      </div>
</div>

<div class="container">
  <h6 class="mt-4 text-center">Marble a VC studio that partners with scientists, engineers and operators to build deeptech startups that slash emissions, remove carbon, and cool the planet.
</h6>

<p class="text-center">
    <button class="btn btn-outline-dark">Art And Photography</button>
    <button class="btn btn-outline-dark">Art And Photography</button>
    <button class="btn btn-outline-dark">Art And Photography</button>
    <button class="btn btn-outline-dark">Art And Photography</button>
    <button class="btn btn-outline-dark">Art And Photography</button>
    
</p>

<p class="text-center mt-2">

    <button class="btn btn-outline-dark">Art And Photography</button>
    <button class="btn btn-outline-dark">Art And Photography</button>
    <button class="btn btn-outline-dark">Art And Photography</button>

  
  
</p>
    <div class="row mt-4">

        <p class="mt-4 text-center">Screen Shots</p>

        <div class="col-md-2"></div>
        <div class="col-md-8">
          {% if project.image %}
          <img src="{{project.image.url}}" alt="" srcset="" width="100%">
          {% else %}
            <img src="{% static 'img/hero.jpg' %}" alt="" srcset="" width="100%">
            {% endif %}

        </div>
        <div class="col-md-2"></div>


        
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <a class="text-dark" href="#">Votes</a>
                    <a class="text-dark" href="#">Judges</a>
                    <a class="text-dark" href="#">Users</a>

                    <table class="table align-middle mb-0 bg-white">
                        <thead class="bg-light">
                          <!-- <tr>
                            <th>Votes</th>
                            <th>Title</th>
                            <th>Status</th>
                            <th>Position</th>
                            <th>Actions</th>
                          </tr> -->
                        </thead>
                        <tbody>
                          {% for rating in rating %}
                          <tr>
                            <td>
                              <div class="d-flex align-items-center">
                                {% if rating.user.profile.image %}
                                <img
                                    src="{{rating.user.profile.image.url}}"
                                    alt=""
                                    style="width: 45px; height: 45px"
                                    class="rounded-circle"
                                    />
                                    {% else %}
                                    <img
                                    src="https://mdbootstrap.com/img/new/avatars/8.jpg"
                                    alt=""
                                    style="width: 45px; height: 45px"
                                    class="rounded-circle"
                                    />
                                    {% endif %} 
                                <div class="ms-3">
                                  <p class="fw-bold mb-1">{{rating.user.profile.user.username}}</p>
                                  <p class="text-muted mb-0">{{rating.user.profile.bio}}</p>
                                </div>
                              </div>
                            </td>
                            <td>
                                <div class="rating text-dark">{{rating.design_rating}}</div>
                            </td>
                            <td>
                                <div class="rating">{{rating.content_rating}}</div>
                            </td>
                            <td>
                                <div class="rating">{{rating.usability_rating}}</div>
                            </td>

                            <td>
                                <p class="text-lg text-dark"><strong>{{rating.user_avg}}</strong></p>
                            </td>
                            
                          </tr>
                          {% endfor %}
                          
                        </tbody>
                      </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% if request.user.is_authenticated %}
    {% if project.user != request.user %}
    <div class="container mt-4 mb-4">
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form | crispy}}
            <button class="btn btn-primary btn-sm mt-2" type="submit">Add Review</button>
        </form>
        </div>
        <div class="col-md-2"></div>
      </div>
    </div>
  
  {% endif %}
  {% endif %}


<!-- Footer -->


<footer class="bg-light text-center text-lg-start mt-4">
    <!-- Grid container -->
    <div class="container p-4">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-lg-8 col-md-12 mb-4 mb-md-0">
          <h5 class="text-uppercase">The awards for design, creativity and innovation on the Internet.
        </h5>
  
          <p>
            Follow us Twitter Facebook Youtube Instagram Linkedin Pinterest
          </p>
        </div>
        <!--Grid column-->
  
        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4 mb-md-0">
          <p class="text-uppercase">Next Conferences  Amsterdam and Tokyo</p>
  
    
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </div>
    <!-- Grid container -->
  
    <!-- Copyright -->
    <div class="row p-4" style="background-color: rgba(0, 0, 0, 0.2);">
      <div class="col-md-8">
        <a class="text-dark text-muted" href="#">
            Contact
            F.A.Q
            Cookies Policy
            Legal Terms
            Privacy Policy
            English</a>
      </div>

      <div class="col-md-4">
        <a href="#">Private Cloud Stack</a>
      </div>
    </div>
    <!-- Copyright -->
  </footer>
    <!--js  -->

    <script src="{% static 'js/main.js' %}"></script>

    <!-- MDB -->
<script
type="text/javascript"
src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.1.0/mdb.min.js"
></script>


  </body>
</html>

templates/edit_profile.html
  {% load static %}
  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Awards</title>
  
      <!-- css mdb -->
  
      <!-- Font Awesome -->
      <link
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        rel="stylesheet"
      />
      <!-- Google Fonts -->
      <link
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        rel="stylesheet"
      />
      <!-- MDB -->
      <link
        href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.1.0/mdb.min.css"
        rel="stylesheet"
      />
  
      <!-- custom css -->
  
      <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  
    </head>
    <body>
  
     
      <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <!-- Container wrapper -->
      <div class="container-fluid">
        <!-- Toggle button -->
        <button
          class="navbar-toggler"
          type="button"
          data-mdb-toggle="collapse"
          data-mdb-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars"></i>
        </button>
        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Navbar brand -->
          <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'home' %}">
          <h5>Awwards</h5>
          </a>
          <!-- Left links -->
          <!-- <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="#">Dashboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Team</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Projects</a>
            </li>
          </ul> -->
          <!-- Left links -->
        </div>
  
        <form class="d-flex input-group w-auto">
          <input
            type="search"
            class="form-control rounded"
            placeholder="Search"
            aria-label="Search"
            aria-describedby="search-addon"
          />
          <span class="input-group-text border-0" id="search-addon">
            <i class="fas fa-search"></i>
          </span>
        </form>
        <!-- Collapsible wrapper -->
    
        <!-- Right elements -->
        <div class="d-flex align-items-center">
  
  
            {% if request.user.is_authenticated %}
            <a class="text-reset me-3" href="#">
              <a href="{% url 'profile' request.user.username %}"
              class="nav-item nav-link {% if request.user.username in request.path %}active{% endif %}">
              Profile page
           </a>
              <a href="{% url 'logout' %}" class="nav-item nav-link">Logout</a>
             </a>
             {% else %}
             <a class="text-reset me-3" href="#">
              <a href="{% url 'signup' %}" class="nav-item nav-link">Register</a>
              <a href="{% url 'login' %}" class="nav-item nav-link">login</a>
              </a>
             {% endif %}
        
         
    
         
        </div>
        <!-- Right elements -->
      </div>
      <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" style="margin-top: 5rem;">
      {{message}}
    </div>
    {% endfor %}
  {% endif %}
  
    <!-- hero -->
  <div class="container mt-4">
    <div class="row mt-4"></div>
  </div>

      <div class="container mt-4">
          <div class="row mt-4">
              <div class="col-md-3 mt-4">

              </div>
              <div class="col-md-6">
      
                <h2 class="my-5">Edit profile</h2>
                <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="form-group">
                    {{ form.username.label_tag }}
                    <input type="text" class="form-control {% if form.username.errors %}is-invalid{% endif %}" id="id_username"
                      name="username" value='{{ form.username.value|default:user.username }}'>
                    {% if form.username.errors %}
                    <div class="invalid-feedback">{{ form.username.errors }}</div>
                    {% endif %}
                  </div>
          
                  <div class="form-group">
                    {{ form.bio.label_tag }}
                    <textarea type="text" class="form-control {% if form.bio.errors %}is-invalid{% endif %}" id="id_bio"
                      name="bio" value='{{ form.bio.value }}' rows="5"></textarea>
                    {% if form.bio.errors %}
                    <div class="invalid-feedback">{{ form.bio.errors }}</div>
                    {% endif %}
                  </div>
          
                  <div class="form-group">
                    {{ form.image.label_tag }}<br>
                    <input type="file" class="{% if form.image.errors %}is-invalid{% endif %}" id="id_image" name="image"
                      accept="image/*">
                    {% if form.image.errors %}
                    <div class="invalid-feedback">{{ form.image.errors }}</div>
                    {% endif %}
                  </div>
          
                  <button type="submit" class="btn btn-primary mt-2">Submit</button>
                </form>
      
                  <div class="row text-center">
      
              
                  </div>
      
      
              </div>
              <div class="col-md-3"></div>
          </div>
  

        </div>

  
  
  
  <!-- Footer -->
  
  
  <footer class="bg-light text-center text-lg-start mt-4">
      <!-- Grid container -->
      <div class="container p-4">
        <!--Grid row-->
        <div class="row">
          <!--Grid column-->
          <div class="col-lg-8 col-md-12 mb-4 mb-md-0">
            <h5 class="text-uppercase">The awards for design, creativity and innovation on the Internet.
          </h5>
    
            <p>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
              molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae
              aliquam voluptatem veniam, est atque cumque eum delectus sint!
            </p>
          </div>
          <!--Grid column-->
    
          <!--Grid column-->
          <div class="col-lg-4 col-md-12 mb-4 mb-md-0">
            <p class="text-uppercase">Next Conferences  Amsterdam and Tokyo</p>
    
      
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </div>
      <!-- Grid container -->
    
      <!-- Copyright -->
      <div class="row p-4" style="background-color: rgba(0, 0, 0, 0.2);">
        <div class="col-md-8">
          <a class="text-dark text-muted" href="#">
              Contact
              F.A.Q
              Cookies Policy
              Legal Terms
              Privacy Policy
              English</a>
        </div>
  
        <div class="col-md-4">
          <a href="#">Private Cloud Stack</a>
        </div>
      </div>
      <!-- Copyright -->
    </footer>
      <!--js  -->
  
      <!-- MDB -->
  <script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.1.0/mdb.min.js"
  ></script>
  
  
    </body>
  </html>
  

templates/index.html
{% load static %}
<nav class="navbar navbar-expand-sm navbar-light bg-light">
    <div class="container">
      <!-- ... -->
      <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
        <!-- ... -->
        {% if request.user.is_authenticated %}
        <div class="navbar-nav ml-auto">
          <a href="{% url 'profile' request.user.username %}"
              class="nav-item nav-link {% if request.user.username in request.path %}active{% endif %}">
              Profile, {{request.user.username}}
           </a>
           <a href="{% url 'postproject' %}" class="nav-item nav-link">post project</a>
          <a href="{% url 'logout' %}" class="nav-item nav-link">Log out</a>
        </div>
        {% else %}
        <a href="{% url 'signup' %}" class="nav-item nav-link">Register</a>
        <a href="{% url 'login' %}" class="nav-item nav-link">login</a>
        {% endif %}
      </div>
    </div>
    
  </nav>
  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" style="margin-top: 5rem;">
    {{message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %}
{% endif %}



{% for project in projects %}
  {% if project.image %}
  <img class="card-img-top col-sm-3 col-4 my-3" src="{{ project.image.url }}" width="100" height="100" alt="{{ project.title }}">
  {% else %}
  <img class="card-img-top col-sm-3 col-4 my-3" src="{% static 'img/avatar.jpg' %}" alt="{{ project.title }}">
  {% endif %}
  <a href="{% url 'projects_details' project.id %}">{{ project.title}}</a>
  <p>{{ project.technologies}}</p>
{% endfor %}

templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row">
      <div class="col-12">
        <h2 class=" my-5">Log in</h2>
        <form method="post">
          {% csrf_token %}
  
          <div class="form-group">
            {{ form.email.label_tag }}
            <input type="email" class="form-control {% if form.email.errors %}is-invalid{% endif %}" id="id_email"
              name="email" value='{{ form.email.value|default:"" }}'>
            {% if form.email.errors %}
            <div class="invalid-feedback">{{ form.email.errors }}</div>
            {% endif %}
          </div>
  
          <div class="form-group">
            {{ form.password.label_tag }}
            <input type="password" class="form-control {% if form.password.errors %}is-invalid{% endif %}"
              id="id_password" name="password" value='{{ form.password.value|default:"" }}'>
            {% if form.password.errors %}
            <div class="invalid-feedback">{{ form.password.errors }}</div>
            {% endif %}
          </div>
  
          <button type="submit" class="btn btn-primary">Sign in</button>
          <p>Already Have an account <span><a href="{% url 'signup' %}" class="nav-item nav-link">Register</a></span></p>
        </form>
      </div>
    </div>
  </div>
  {% endblock content %}

templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="row">
      <div class="col-12">
        <h2 class="my-5">Sign up</h2>
        <form method="post">
          {% csrf_token %}

          <div class="form-group">
            {{ form.username.label_tag }}
            <input type="text" class="form-control {% if form.username.errors %}is-invalid{% endif %}" id="id_username"
              name="username" value='{{ form.username.value|default:"" }}'>
            {% if form.username.errors %}
            <div class="invalid-feedback">{{ form.username.errors }}</div>
            {% endif %}
            <small class="text-muted">{{ form.username.help_text }}</small>
          </div>
          
          <div class="form-group">
            {{ form.email.label_tag }}
            <input type="email" class="form-control {% if form.email.errors %}is-invalid{% endif %}" id="id_email"
              name="email" value='{{ form.email.value|default:"" }}'>
            {% if form.email.errors %}
            <div class="invalid-feedback">{{ form.email.errors }}</div>
            {% endif %}
          </div>
          
          <div class="form-group">
            {{ form.password1.label_tag }}
            <input type="password" class="form-control {% if form.password1.errors %}is-invalid{% endif %}"
              id="id_password1" name="password1" value='{{ form.password1.value|default:"" }}'>
            {% if form.password1.errors %}
            <div class="invalid-feedback">{{ form.password1.errors }}</div>
            {% endif %}
            <small class="text-muted">{{ form.password1.help_text }}</small>
          </div>
  
          <div class="form-group">
            {{ form.password2.label_tag }}
            <input type="password" class="form-control {% if form.password2.errors %}is-invalid{% endif %}"
              id="id_password2" name="password2" value='{{ form.password2.value|default:"" }}'>
            <small class="text-muted">{{ form.password2.help_text }}</small>
            {% if form.password2.errors %}
            <div class="invalid-feedback">{{ form.password2.errors }}</div>
            {% endif %}
          </div>
          <button type="submit" class="btn btn-primary">Sign up</button>
          <p>Already Have an account <span><a href="{% url 'login' %}" class="nav-item nav-link">login</a></span></p>
        </form>
       
      </div>
    </div>
  </div>
  {% endblock content %}

templates/updateproject.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>update blog</title>
</head>
<body>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" style="margin-top: 5rem;">
      {{message}}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
{% endif %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">save</button>
    </form>
    
</body>
</html>